const AtomicSymbol = [ // An array of Atomic elements. Use = AtomicSymbol[<element>]. name: Name of element (str); shortform: Element intials (str); aanConst: Atomic number (int) ; group: Group on periodic table (int) ; period: Period on periodic table (int) 
    {
        name: "N/A",
        shortform: "N/A",
        aanConst: 0, 
        group: -1,
        period: -1,
        avgMass: -1,
    },
    {
        name: "Hydrogen",
        shortform: "H",
        aanConst: 1, //Atomic number. Used aanConst so that it wouldn't get confused with var aan
        group: 1,
        period: 1,
        avgMass: 1.0078,
    },
    {
        name: "Helium",
        shortform: "He",
        aanConst: 2, 
        group: 18,
        period: 1,
        avgMass: 4.0026,
    },
    {
        name: "Lithium",
        shortform: "Li",
        aanConst: 3, 
        group: 1,
        period: 2,
        avgMass: 6.9410,
    },
    {
        name: "Beryllium",
        shortform: "Be",
        aanConst: 4, 
        group: 2,
        period: 2,
        avgMass: 4.0026,
    },
    {
        name: "Boron",
        shortform: "B",
        aanConst: 5, 
        group: 13,
        period: 2,
        avgMass: 10.811,
    },
    {
        name: "Carbon",
        shortform: "C",
        aanConst: 6, 
        group: 14,
        period: 2,
        avgMass: 12.011,
    },
    {
        name: "Nitrogen",
        shortform: "N",
        aanConst: 7, 
        group: 15,
        period: 2,
        avgMass: 14.007,
    },
    {
        name: "Oxygen",
        shortform: "O",
        aanConst: 8, 
        group: 16,
        period: 2,
        avgMass: 15.999,
    },
    {
        name: "Fluorine",
        shortform: "F",
        aanConst: 9, 
        group: 17,
        period: 2,
        avgMass: 18.998,
    },
    {
        name: "Neon",
        shortform: "Ne",
        aanConst: 10, 
        group: 18,
        period: 2,
        avgMass: 20.180,
    },    {
        name: "Sodium",
        shortform: "Na",
        aanConst: 11, 
        group: 1,
        period: 3,
        avgMass: 22.990,
    },
    {
        name: "Magnesium",
        shortform: "Mg",
        aanConst: 12, 
        group: 2,
        period: 3,
        avgMass: 24.305,
    },
    {
        name: "Aluminium", // I pronounce it the British way *sunglasses emoji*
        shortform: "Al",
        aanConst: 13, 
        group: 13,
        period: 3,
        avgMass: 26.982,
    },
    {
        name: "Silicon",
        shortform: "Si",
        aanConst: 14, 
        group: 14,
        period: 3,
        avgMass: 28.085,
    },
    {
        name: "Phosphorus",
        shortform: "P",
        aanConst: 15, 
        group: 15,
        period: 3,
        avgMass: 30.974,
    },
    {
        name: "Sulphur",
        shortform: "S",
        aanConst: 16, 
        group: 16,
        period: 3,
        avgMass: 32.065,
    },    {
        name: "Chlorine",
        shortform: "Cl",
        aanConst: 17, 
        group: 17,
        period: 3,
        avgMass: 35.453,
    },
    {
        name: "Argon",
        shortform: "Ar",
        aanConst: 18, 
        group: 18,
        period: 3,
        avgMass: 39.948,
    },
    {
        name: "Potassium",
        shortform: "K",
        aanConst: 19, 
        group: 1,
        period: 4,
        avgMass: 39.098,
    },
    {
        name: "Calcium",
        shortform: "Ca",
        aanConst: 20, 
        group: 2,
        period: 4,
        avgMass: 40.078,
    },
    {
        name: "Scandium",
        shortform: "Sc",
        aanConst: 21, 
        group: 3,
        period: 4,
        avgMass: 44.956,
    },
    {
        name: "Titanium",
        shortform: "Ti",
        aanConst: 22, 
        group: 4,
        period: 4,
        avgMass: 47.867,
    },
    {
        name: "Vanadium",
        shortform: "V",
        aanConst: 23, 
        group: 5,
        period: 4,
        avgMass: 50.942,
    },
    {
        name: "Chromium",
        shortform: "Cr",
        aanConst: 24, 
        group: 6,
        period: 4,
        avgMass: 51.996,
    },
    {
        name: "Manganese",
        shortform: "Mn",
        aanConst: 25, 
        group: 7,
        period: 4,
        avgMass: 54.938,
    },    
    {
        name: "Iron",
        shortform: "Fe",
        aanConst: 26, 
        group: 8,
        period: 4,
        avgMass: 55.845,
    },
    {
        name: "Cobalt",
        shortform: "Co",
        aanConst: 27, 
        group: 9,
        period: 4,
        avgMass: 58.933,
    },
    {
        name: "Nickel",
        shortform: "Ni",
        aanConst: 28, 
        group: 10,
        period: 4,
        avgMass: 58.693,
    },
    {
        name: "Copper",
        shortform: "Cu",
        aanConst: 29, 
        group: 11,
        period: 4,
        avgMass: 63.546,
    },
    {
        name: "Zinc",
        shortform: "Zn",
        aanConst: 30, 
        group: 12,
        period: 4,
        avgMass: 65.38,
    },
    {
        name: "Gallium",
        shortform: "Ga",
        aanConst: 31, 
        group: 13,
        period: 4,
        avgMass: 69.723,
    },
    {
        name: "Germanium",
        shortform: "Ge",
        aanConst: 32, 
        group: 14,
        period: 4,
        avgMass: 72.63,
    },
    {
        name: "Arsenic",
        shortform: "As",
        aanConst: 33, 
        group: 15,
        period: 4,
        avgMass: 74.922,
    },
    {
        name: "Selenium",
        shortform: "Se",
        aanConst: 34, 
        group: 16,
        period: 4,
        avgMass: 78.971,
    },
    {
        name: "Bromine",
        shortform: "Br",
        aanConst: 35, 
        group: 17,
        period: 4,
        avgMass: 79.904,
    },
    {
        name: "Krypton",
        shortform: "Kr",
        aanConst: 36, 
        group: 18,
        period: 4,
        avgMass: 83.798,
    },
    {
        name: "Rubidium",
        shortform: "Rb",
        aanConst: 37, 
        group: 1,
        period: 5,
        avgMass: 85.468,
    },
    {
        name: "Strontium",
        shortform: "Sr",
        aanConst: 38, 
        group: 2,
        period: 5,
        avgMass: 87.62,
    },
    {
        name: "Yttrium",
        shortform: "Y",
        aanConst: 39, 
        group: 3,
        period: 5,
        avgMass: 88.906,
    },
    {
        name: "Zirconium",
        shortform: "Zn",
        aanConst: 40, 
        group: 4,
        period: 5,
        avgMass: 91.224,
    },
    {
        name: "Niobium",
        shortform: "Nb",
        aanConst: 41, 
        group: 5,
        period: 5,
        avgMass: 92.906,
    },
    {
        name: "Molybdenum",
        shortform: "Mo",
        aanConst: 42, 
        group: 6,
        period: 5,
        avgMass: 95.95,
    },
    {
        name: "Technetium",
        shortform: "Tc",
        aanConst: 43, 
        group: 7,
        period: 5,
        avgMass: 98,
    },
    {
        name: "Ruthenium",
        shortform: "Ru",
        aanConst: 44, 
        group: 8,
        period: 5,
        avgMass: 101.07,
    },
    {
        name: "Rhodium",
        shortform: "Zn",
        aanConst: 45, 
        group: 9,
        period: 5,
        avgMass: 102.91,
    },
    {
        name: "Palladium",
        shortform: "Pd",
        aanConst: 46, 
        group: 10,
        period: 5,
        avgMass: 106.42,
    },
    {
        name: "Silver",
        shortform: "Ag",
        aanConst: 47, 
        group: 11,
        period: 5,
        avgMass: 107.87,
    },
    {
        name: "Cadmium",
        shortform: "Cd",
        aanConst: 48, 
        group: 12,
        period: 5,
        avgMass: 112.41,
    },
    {
        name: "Indium",
        shortform: "In",
        aanConst: 49, 
        group: 13,
        period: 5,
        avgMass: 114.82,
    },
    {
        name: "Tin",
        shortform: "Sn",
        aanConst: 50, 
        group: 14,
        period: 5,
        avgMass: 118.71,
    },
    {
        name: "Antimony",
        shortform: "Sb",
        aanConst: 51, 
        group: 15,
        period: 5,
        avgMass: 121.76,
    },
    {
        name: "Tellurium",
        shortform: "Te",
        aanConst: 52, 
        group: 16,
        period: 5,
        avgMass: 127.6,
    },
    {
        name: "Iodine",
        shortform: "I",
        aanConst: 53, 
        group: 17,
        period: 5,
        avgMass: 126.9,
    },
    {
        name: "Xenon",
        shortform: "Xe",
        aanConst: 54, 
        group: 18,
        period: 5,
        avgMass: 131.29,
    },
    {
        name: "Caesium",
        shortform: "Cs",
        aanConst: 55, 
        group: 1,
        period: 6,
        avgMass: 132.91,
    },
    {
        name: "Barium",
        shortform: "Ba",
        aanConst: 56, 
        group: 2,
        period: 6,
        avgMass: 137.33,
    },
    {
        name: "Lanthanum",
        shortform: "La",
        aanConst: 57, 
        group: "N/A",
        period: 6,
        avgMass: 138.905,
    },
    {
        name: "Cerium",
        shortform: "Ce",
        aanConst: 58, 
        group: "N/A",
        period: 6,
        avgMass: 140.116,
    },
    {
        name: "Praseodymium",
        shortform: "Pr",
        aanConst: 59, 
        group: "N/A",
        period: 6,
        avgMass: 140.907,
    },
    {
        name: "Neodymium",
        shortform: "Nd",
        aanConst: 60, 
        group: "N/A",
        period: 6,
        avgMass: 144.242,
    },
    {
        name: "Promethium",
        shortform: "Pm",
        aanConst: 61, 
        group: "N/A",
        period: 6,
        avgMass: 145,
    },
    {
        name: "Samarium",
        shortform: "Sm",
        aanConst: 62, 
        group: "N/A",
        period: 6,
        avgMass: 150.36,
    },
    {
        name: "Europium",
        shortform: "Eu",
        aanConst: 63, 
        group: "N/A",
        period: 6,
        avgMass: 151.964,
    },
    {
        name: "Gadolinium",
        shortform: "Gd",
        aanConst: 64, 
        group: "N/A",
        period: 6,
        avgMass: 157.25,
    },
    {
        name: "Terbium",
        shortform: "Tb",
        aanConst: 65, 
        group: "N/A",
        period: 6,
        avgMass: 158.925,
    },
    {
        name: "Dysprosium",
        shortform: "Dy",
        aanConst: 66, 
        group: "N/A",
        period: 6,
        avgMass: 162.5,
    },
    {
        name: "Holmium",
        shortform: "Ho",
        aanConst: 67, 
        group: "N/A",
        period: 6,
        avgMass: 164.93,
    },
    {
        name: "Erbium",
        shortform: "Er",
        aanConst: 68, 
        group: "N/A",
        period: 6,
        avgMass: 167.259,
    },
    {
        name: "Thulium",
        shortform: "Tm",
        aanConst: 69, 
        group: "N/A",
        period: 6,
        avgMass: 168.934,
    },    {
        name: "Ytterbium",
        shortform: "Yb",
        aanConst: 70, 
        group: "N/A",
        period: 6,
        avgMass: 173.045,
    },
    {
        name: "Lutetium",
        shortform: "Lu",
        aanConst: 71, 
        group: 3,
        period: 6,
        avgMass: 174.966,
    },
    {
        name: "Hafnium",
        shortform: "Hf",
        aanConst: 72, 
        group: 4,
        period: 6,
        avgMass: 178.49,
    },
    {
        name: "Tantalum",
        shortform: "Ta",
        aanConst: 73, 
        group: 5,
        period: 6,
        avgMass: 180.948,
    },
    {
        name: "Tungsten",
        shortform: "W",
        aanConst: 74, 
        group: 6,
        period: 6,
        avgMass: 183.84,
    },
    {
        name: "Rhenium",
        shortform: "Re",
        aanConst: 75, 
        group: 7,
        period: 6,
        avgMass: 186.207,
    },
    {
        name: "Osmium",
        shortform: "Os",
        aanConst: 76, 
        group: 8,
        period: 6,
        avgMass: 190.23,
    },
    {
        name: "Iridium",
        shortform: "Ir",
        aanConst: 77, 
        group: 9,
        period: 6,
        avgMass: 192.217,
    },
    {
        name: "Platinum",
        shortform: "Pt",
        aanConst: 78, 
        group: 10,
        period: 6,
        avgMass: 195.084,
    },
    {
        name: "Gold",
        shortform: "Au",
        aanConst: 79, 
        group: 11,
        period: 6,
        avgMass: 196.967,
    },
    {
        name: "Mercury",
        shortform: "Hg",
        aanConst: 80, 
        group: 12,
        period: 6,
        avgMass: 200.592,
    },
    {
        name: "Thallium",
        shortform: "Tl",
        aanConst: 81, 
        group: 13,
        period: 6,
        avgMass: 204.38,
    },
    {
        name: "Lead",
        shortform: "Pb",
        aanConst: 82, 
        group: 14,
        period: 6,
        avgMass: 207.2,
    },    
    {
        name: "Bismuth",
        shortform: "Bi",
        aanConst: 83, 
        group: 15,
        period: 6,
        avgMass: 208.980,
    },
    {
        name: "Polonium",
        shortform: "Po",
        aanConst: 84, 
        group: 16,
        period: 6,
        avgMass: 209,
    },
    {
        name: "Astatine",
        shortform: "At",
        aanConst: 85, 
        group: 17,
        period: 6,
        avgMass: 210,
    },
    {
        name: "Radon",
        shortform: "Rn",
        aanConst: 86, 
        group: 18,
        period: 6,
        avgMass: 222,
    },
    {
        name: "Francium",
        shortform: "Fr",
        aanConst: 87, 
        group: 1,
        period: 7,
        avgMass: 223,
    },
    {
        name: "Radium",
        shortform: "Ra",
        aanConst: 88, 
        group: 2,
        period: 7,
        avgMass: 226,
    },
    {
        name: "Actinium",
        shortform: "Ac",
        aanConst: 89, 
        group: "N/A",
        period: 7,
        avgMass: 227,
    },
    {
        name: "Thorium",
        shortform: "Th",
        aanConst: 90, 
        group: "N/A",
        period: 7,
        avgMass: 232.038,
    },
    {
        name: "Protactinium",
        shortform: "Pa",
        aanConst: 91, 
        group: "N/A",
        period: 7,
        avgMass: 231.036,
    },
    {
        name: "Uranium",
        shortform: "U",
        aanConst: 92, 
        group: "N/A",
        period: 7,
        avgMass: 238.029,
    },
    {
        name: "Neptunium",
        shortform: "Np",
        aanConst: 93, 
        group: "N/A",
        period: 7,
        avgMass: 237,
    },
    {
        name: "Plutonium",
        shortform: "Pu",
        aanConst: 94, 
        group: "N/A",
        period: 7,
        avgMass: 244,
    },
    {
        name: "Americium",
        shortform: "Am",
        aanConst: 95, 
        group: "N/A",
        period: 7,
        avgMass: 243,
    },
    {
        name: "Curium",
        shortform: "Cm",
        aanConst: 96, 
        group: "N/A",
        period: 7,
        avgMass: 247,
    },
    {
        name: "Berkelium",
        shortform: "Bk",
        aanConst: 97, 
        group: "N/A",
        period: 7,
        avgMass: 247,
    },
    {
        name: "Californium",
        shortform: "Cf",
        aanConst: 98, 
        group: "N/A",
        period: 7,
        avgMass: 251,
    },    {
        name: "Einsteinium",
        shortform: "Es",
        aanConst: 99, 
        group: "N/A",
        period: 7,
        avgMass: 252,
    },
    {
        name: "Fermium",
        shortform: "Fm",
        aanConst: 100, 
        group: "N/A",
        period: 7,
        avgMass: 257,
    },
    {
        name: "Mendelevium",
        shortform: "Md",
        aanConst: 101, 
        group: "N/A",
        period: 7,
        avgMass: 258,
    },
    {
        name: "Nobelium",
        shortform: "No",
        aanConst: 102, 
        group: "N/A",
        period: 7,
        avgMass: 259,
    },
    {
        name: "Lawrencium",
        shortform: "Lr",
        aanConst: 103, 
        group: 3,
        period: 7,
        avgMass: 266,
    },
    {
        name: "Rutherfordium",
        shortform: "Rf",
        aanConst: 104, 
        group: 4,
        period: 7,
        avgMass: 267,
    },
    {
        name: "Dubnium",
        shortform: "Db",
        aanConst: 105, 
        group: 5,
        period: 7,
        avgMass: 268,
    },
    {
        name: "Seaborgium",
        shortform: "Sg",
        aanConst: 106, 
        group: 6,
        period: 7,
        avgMass: 269,
    },
    {
        name: "Bohrium",
        shortform: "Bh",
        aanConst: 107, 
        group: 7,
        period: 7,
        avgMass: 270,
    },
    {
        name: "Hassium",
        shortform: "Hs",
        aanConst: 108, 
        group: 8,
        period: 7,
        avgMass: 277,
    },
    {
        name: "Meitnerium",
        shortform: "Mt",
        aanConst: 109, 
        group: 9,
        period: 7,
        avgMass: 278,
    },
    {
        name: "Darmstadtium",
        shortform: "Ds",
        aanConst: 110, 
        group: 10,
        period: 7,
        avgMass: 281,
    },
    {
        name: "Roentgenium",
        shortform: "Rg",
        aanConst: 111, 
        group: 11,
        period: 7,
        avgMass: 282,
    },
    {
        name: "Copernicium",
        shortform: "Cn",
        aanConst: 112, 
        group: 12,
        period: 7,
        avgMass: 285,
    },
    {
        name: "Nihonium",
        shortform: "Nh",
        aanConst: 113, 
        group: 13,
        period: 7,
        avgMass: 286,
    },
    {
        name: "Flerovium",
        shortform: "Fl",
        aanConst: 114, 
        group: 14,
        period: 7,
        avgMass: 289,
    },
    {
        name: "Moscovium",
        shortform: "Mc",
        aanConst: 115, 
        group: 15,
        period: 7,
        avgMass: 290,
    },
    {
        name: "Livermorium",
        shortform: "Lc",
        aanConst: 116, 
        group: 16,
        period: 7,
        avgMass: 293,
    },
    {
        name: "Tennessine",
        shortform: "Ts",
        aanConst: 117, 
        group: 17,
        period: 7,
        avgMass: 294,
    },
    {
        name: "Oganesson",
        shortform: "Og",
        aanConst: 118, 
        group: 18,
        period: 7,
        avgMass: 294,
    },
];